version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: ajv
    versions:
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: "@types/js-yaml"
    versions:
    - 4.0.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
